### ISSUE TITLE
problems after podman update 

### ISSUE THREAD

**Issue by ayocam** [unifi-utilities/unifios-utilities#385]
After I updated podman if I try to go to unifi-os shell I get this:

WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus: open /sys/fs/cgroup/libpod_parent/conmon/cpuset.cpus.effective: no such file or directory
Error: OCI runtime error: panic: expected "name=systemd" path to be unified path "/sys/fs/cgroup/devices/libpod_parent/libpod-50a26157032021479b4b75c3339b5cefc30812de317e62aa1fdd9cb934290cbc", got "/sys/fs/cgroup/systemd/libpod_parent/libpod-50a26157032021479b4b75c3339b5cefc30812de317e62aa1fdd9cb934290cbc"

goroutine 1 [running]:
github.com/opencontainers/runc/libcontainer.getUnifiedPath(0x4000250e40, 0x5558e2b400, 0x0)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:59 +0x2cc
github.com/opencontainers/runc/libcontainer.cgroupfs2.func1(0x4000161730, 0x4000250e40, 0x4a, 0x7fcdc8aedf)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:111 +0x30
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).Load(0x400020c000, 0x7fcdc8aedf, 0x40, 0x0, 0x0, 0x1, 0x8)
	github.com/opencontainers/runc/libcontainer/factory_linux.go:321 +0x14c
main.getContainer(0x4000206160, 0x5558e3be78, 0x8, 0x1, 0x4000153393)
	github.com/opencontainers/runc/utils_linux.go:89 +0x9c
main.execProcess(0x4000206160, 0x0, 0x0, 0x0)
	github.com/opencontainers/runc/exec.go:114 +0x30
main.glob..func5(0x4000206160, 0x555925f3c0, 0x40001534f8)
	github.com/opencontainers/runc/exec.go:104 +0x6c
github.com/urfave/cli.HandleAction(0x5558f2cd60, 0x5558fd9bc8, 0x4000206160, 0x4000206160, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:523 +0x124
github.com/urfave/cli.Command.Run(0x5558e37f3e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5558e4fb5a, 0x28, 0x0, ...)
	github.com/urfave/cli@v1.22.1/command.go:174 +0x408
github.com/urfave/cli.(*App).Run(0x400013c000, 0x40000c2000, 0xe, 0xe, 0x0, 0x0)
	github.com/urfave/cli@v1.22.1/app.go:276 +0x588
main.main()
	github.com/opencontainers/runc/main.go:163 +0xa78

This is a remote machine I will not be able to be on-site with for a while so any help would be much appreciated.

**Comment by simkin** [comment]
**UDM Information**
 - Variant [e.g. Dream Machine, Dream Machine Pro]
 - Firmware Version: [e.g. 1.6.3, 1.7.2-rc4]
 - Controller Version [e.g 5.14.9]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by ayocam** [comment]
not helpful, but thanks...

UniFi OS UDM Pro 1.12.22

I listed the steps to reproduce...  I said I updated podman per the instructions in this git, and when I run unifi-os shell, which is ran by typing 'unifi-os shell' at that point what I pasted above is produced?   How do I fix it to drop me into said shell instead of telling me what it tells me?

**Comment by JoeOIVOV** [comment]
latest compatible firmware with that podman update script:
https://fw-download.ubnt.com/data/udm/f659-udmpro-1.10.4-5ca6bddc
fdaa4e5c9ad0f19668120e37.bin

should just need to remove the script, /mnt/data/on_boot.d/01-podman_update.sh  and reboot and it will work again but, theres no fix at this time.

i actually had to factory reset it, to fix it on my end. after the firmware downgrade I couldn't get into the webgui.
